name: Test App Token

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-app-token:

  - name: Generate GitHub App token
    id: app-token
    uses: actions/create-github-app-token@v2
    with:
      app-id: ${{ vars.MY_APP_ID }}
      private-key: ${{ secrets.MY_APP_PRIVATE_KEY }}
      owner: ${{ github.repository_owner }}
      repositories: ${{ github.event.repository.name }}

  - name: Test /app
    run: |
      curl -i \
        -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/app

  - name: Test /user
    run: |
      curl -i \
        -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/user

  - name: Test /installation
    run: |
      curl -i \
        -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/installation
